<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Comprehensive200CountriesSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            // Middle East & North Africa (18 countries)
            ['name_en' => 'Egypt', 'name_ar' => 'مصر', 'code' => 'EG', 'phone_code' => '+20', 'currency_code' => 'EGP', 'currency_symbol' => 'ج.م'],
            ['name_en' => 'Saudi Arabia', 'name_ar' => 'السعودية', 'code' => 'SA', 'phone_code' => '+966', 'currency_code' => 'SAR', 'currency_symbol' => 'ر.س'],
            ['name_en' => 'United Arab Emirates', 'name_ar' => 'الإمارات', 'code' => 'AE', 'phone_code' => '+971', 'currency_code' => 'AED', 'currency_symbol' => 'د.إ'],
            ['name_en' => 'Kuwait', 'name_ar' => 'الكويت', 'code' => 'KW', 'phone_code' => '+965', 'currency_code' => 'KWD', 'currency_symbol' => 'د.ك'],
            ['name_en' => 'Qatar', 'name_ar' => 'قطر', 'code' => 'QA', 'phone_code' => '+974', 'currency_code' => 'QAR', 'currency_symbol' => 'ر.ق'],
            ['name_en' => 'Bahrain', 'name_ar' => 'البحرين', 'code' => 'BH', 'phone_code' => '+973', 'currency_code' => 'BHD', 'currency_symbol' => 'د.ب'],
            ['name_en' => 'Oman', 'name_ar' => 'عمان', 'code' => 'OM', 'phone_code' => '+968', 'currency_code' => 'OMR', 'currency_symbol' => 'ر.ع'],
            ['name_en' => 'Jordan', 'name_ar' => 'الأردن', 'code' => 'JO', 'phone_code' => '+962', 'currency_code' => 'JOD', 'currency_symbol' => 'د.ا'],
            ['name_en' => 'Lebanon', 'name_ar' => 'لبنان', 'code' => 'LB', 'phone_code' => '+961', 'currency_code' => 'LBP', 'currency_symbol' => 'ل.ل'],
            ['name_en' => 'Iraq', 'name_ar' => 'العراق', 'code' => 'IQ', 'phone_code' => '+964', 'currency_code' => 'IQD', 'currency_symbol' => 'د.ع'],
            ['name_en' => 'Palestine', 'name_ar' => 'فلسطين', 'code' => 'PS', 'phone_code' => '+970', 'currency_code' => 'ILS', 'currency_symbol' => '₪'],
            ['name_en' => 'Syria', 'name_ar' => 'سوريا', 'code' => 'SY', 'phone_code' => '+963', 'currency_code' => 'SYP', 'currency_symbol' => 'ل.س'],
            ['name_en' => 'Yemen', 'name_ar' => 'اليمن', 'code' => 'YE', 'phone_code' => '+967', 'currency_code' => 'YER', 'currency_symbol' => 'ر.ي'],
            ['name_en' => 'Libya', 'name_ar' => 'ليبيا', 'code' => 'LY', 'phone_code' => '+218', 'currency_code' => 'LYD', 'currency_symbol' => 'ل.د'],
            ['name_en' => 'Tunisia', 'name_ar' => 'تونس', 'code' => 'TN', 'phone_code' => '+216', 'currency_code' => 'TND', 'currency_symbol' => 'د.ت'],
            ['name_en' => 'Algeria', 'name_ar' => 'الجزائر', 'code' => 'DZ', 'phone_code' => '+213', 'currency_code' => 'DZD', 'currency_symbol' => 'د.ج'],
            ['name_en' => 'Morocco', 'name_ar' => 'المغرب', 'code' => 'MA', 'phone_code' => '+212', 'currency_code' => 'MAD', 'currency_symbol' => 'د.م'],
            ['name_en' => 'Sudan', 'name_ar' => 'السودان', 'code' => 'SD', 'phone_code' => '+249', 'currency_code' => 'SDG', 'currency_symbol' => 'ج.س'],
            
            // Europe (44 countries)
            ['name_en' => 'United Kingdom', 'name_ar' => 'بريطانيا', 'code' => 'GB', 'phone_code' => '+44', 'currency_code' => 'GBP', 'currency_symbol' => '£'],
            ['name_en' => 'Germany', 'name_ar' => 'ألمانيا', 'code' => 'DE', 'phone_code' => '+49', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'France', 'name_ar' => 'فرنسا', 'code' => 'FR', 'phone_code' => '+33', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Italy', 'name_ar' => 'إيطاليا', 'code' => 'IT', 'phone_code' => '+39', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Spain', 'name_ar' => 'إسبانيا', 'code' => 'ES', 'phone_code' => '+34', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Netherlands', 'name_ar' => 'هولندا', 'code' => 'NL', 'phone_code' => '+31', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Belgium', 'name_ar' => 'بلجيكا', 'code' => 'BE', 'phone_code' => '+32', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Switzerland', 'name_ar' => 'سويسرا', 'code' => 'CH', 'phone_code' => '+41', 'currency_code' => 'CHF', 'currency_symbol' => 'Fr'],
            ['name_en' => 'Austria', 'name_ar' => 'النمسا', 'code' => 'AT', 'phone_code' => '+43', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Sweden', 'name_ar' => 'السويد', 'code' => 'SE', 'phone_code' => '+46', 'currency_code' => 'SEK', 'currency_symbol' => 'kr'],
            ['name_en' => 'Norway', 'name_ar' => 'النرويج', 'code' => 'NO', 'phone_code' => '+47', 'currency_code' => 'NOK', 'currency_symbol' => 'kr'],
            ['name_en' => 'Denmark', 'name_ar' => 'الدنمارك', 'code' => 'DK', 'phone_code' => '+45', 'currency_code' => 'DKK', 'currency_symbol' => 'kr'],
            ['name_en' => 'Finland', 'name_ar' => 'فنلندا', 'code' => 'FI', 'phone_code' => '+358', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Poland', 'name_ar' => 'بولندا', 'code' => 'PL', 'phone_code' => '+48', 'currency_code' => 'PLN', 'currency_symbol' => 'zł'],
            ['name_en' => 'Portugal', 'name_ar' => 'البرتغال', 'code' => 'PT', 'phone_code' => '+351', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Greece', 'name_ar' => 'اليونان', 'code' => 'GR', 'phone_code' => '+30', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Czech Republic', 'name_ar' => 'التشيك', 'code' => 'CZ', 'phone_code' => '+420', 'currency_code' => 'CZK', 'currency_symbol' => 'Kč'],
            ['name_en' => 'Hungary', 'name_ar' => 'المجر', 'code' => 'HU', 'phone_code' => '+36', 'currency_code' => 'HUF', 'currency_symbol' => 'Ft'],
            ['name_en' => 'Romania', 'name_ar' => 'رومانيا', 'code' => 'RO', 'phone_code' => '+40', 'currency_code' => 'RON', 'currency_symbol' => 'lei'],
            ['name_en' => 'Bulgaria', 'name_ar' => 'بلغاريا', 'code' => 'BG', 'phone_code' => '+359', 'currency_code' => 'BGN', 'currency_symbol' => 'лв'],
            ['name_en' => 'Turkey', 'name_ar' => 'تركيا', 'code' => 'TR', 'phone_code' => '+90', 'currency_code' => 'TRY', 'currency_symbol' => '₺'],
            ['name_en' => 'Russia', 'name_ar' => 'روسيا', 'code' => 'RU', 'phone_code' => '+7', 'currency_code' => 'RUB', 'currency_symbol' => '₽'],
            ['name_en' => 'Ukraine', 'name_ar' => 'أوكرانيا', 'code' => 'UA', 'phone_code' => '+380', 'currency_code' => 'UAH', 'currency_symbol' => '₴'],
            ['name_en' => 'Ireland', 'name_ar' => 'أيرلندا', 'code' => 'IE', 'phone_code' => '+353', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Iceland', 'name_ar' => 'آيسلندا', 'code' => 'IS', 'phone_code' => '+354', 'currency_code' => 'ISK', 'currency_symbol' => 'kr'],
            ['name_en' => 'Croatia', 'name_ar' => 'كرواتيا', 'code' => 'HR', 'phone_code' => '+385', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Serbia', 'name_ar' => 'صربيا', 'code' => 'RS', 'phone_code' => '+381', 'currency_code' => 'RSD', 'currency_symbol' => 'дин'],
            ['name_en' => 'Slovakia', 'name_ar' => 'سلوفاكيا', 'code' => 'SK', 'phone_code' => '+421', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Slovenia', 'name_ar' => 'سلوفينيا', 'code' => 'SI', 'phone_code' => '+386', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Lithuania', 'name_ar' => 'ليتوانيا', 'code' => 'LT', 'phone_code' => '+370', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Latvia', 'name_ar' => 'لاتفيا', 'code' => 'LV', 'phone_code' => '+371', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Estonia', 'name_ar' => 'إستونيا', 'code' => 'EE', 'phone_code' => '+372', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Luxembourg', 'name_ar' => 'لوكسمبورغ', 'code' => 'LU', 'phone_code' => '+352', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Malta', 'name_ar' => 'مالطا', 'code' => 'MT', 'phone_code' => '+356', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Cyprus', 'name_ar' => 'قبرص', 'code' => 'CY', 'phone_code' => '+357', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Albania', 'name_ar' => 'ألبانيا', 'code' => 'AL', 'phone_code' => '+355', 'currency_code' => 'ALL', 'currency_symbol' => 'L'],
            ['name_en' => 'Bosnia and Herzegovina', 'name_ar' => 'البوسنة والهرسك', 'code' => 'BA', 'phone_code' => '+387', 'currency_code' => 'BAM', 'currency_symbol' => 'KM'],
            ['name_en' => 'North Macedonia', 'name_ar' => 'مقدونيا الشمالية', 'code' => 'MK', 'phone_code' => '+389', 'currency_code' => 'MKD', 'currency_symbol' => 'ден'],
            ['name_en' => 'Montenegro', 'name_ar' => 'الجبل الأسود', 'code' => 'ME', 'phone_code' => '+382', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Moldova', 'name_ar' => 'مولدوفا', 'code' => 'MD', 'phone_code' => '+373', 'currency_code' => 'MDL', 'currency_symbol' => 'L'],
            ['name_en' => 'Belarus', 'name_ar' => 'بيلاروسيا', 'code' => 'BY', 'phone_code' => '+375', 'currency_code' => 'BYN', 'currency_symbol' => 'Br'],
            ['name_en' => 'Monaco', 'name_ar' => 'موناكو', 'code' => 'MC', 'phone_code' => '+377', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name_en' => 'Liechtenstein', 'name_ar' => 'ليختنشتاين', 'code' => 'LI', 'phone_code' => '+423', 'currency_code' => 'CHF', 'currency_symbol' => 'Fr'],

            // Americas (35 countries)
            ['name_en' => 'United States', 'name_ar' => 'الولايات المتحدة', 'code' => 'US', 'phone_code' => '+1', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name_en' => 'Canada', 'name_ar' => 'كندا', 'code' => 'CA', 'phone_code' => '+1', 'currency_code' => 'CAD', 'currency_symbol' => 'C$'],
            ['name_en' => 'Mexico', 'name_ar' => 'المكسيك', 'code' => 'MX', 'phone_code' => '+52', 'currency_code' => 'MXN', 'currency_symbol' => '$'],
            ['name_en' => 'Brazil', 'name_ar' => 'البرازيل', 'code' => 'BR', 'phone_code' => '+55', 'currency_code' => 'BRL', 'currency_symbol' => 'R$'],
            ['name_en' => 'Argentina', 'name_ar' => 'الأرجنتين', 'code' => 'AR', 'phone_code' => '+54', 'currency_code' => 'ARS', 'currency_symbol' => '$'],
            ['name_en' => 'Chile', 'name_ar' => 'تشيلي', 'code' => 'CL', 'phone_code' => '+56', 'currency_code' => 'CLP', 'currency_symbol' => '$'],
            ['name_en' => 'Colombia', 'name_ar' => 'كولومبيا', 'code' => 'CO', 'phone_code' => '+57', 'currency_code' => 'COP', 'currency_symbol' => '$'],
            ['name_en' => 'Peru', 'name_ar' => 'بيرو', 'code' => 'PE', 'phone_code' => '+51', 'currency_code' => 'PEN', 'currency_symbol' => 'S/'],
            ['name_en' => 'Venezuela', 'name_ar' => 'فنزويلا', 'code' => 'VE', 'phone_code' => '+58', 'currency_code' => 'VES', 'currency_symbol' => 'Bs'],
            ['name_en' => 'Ecuador', 'name_ar' => 'الإكوادور', 'code' => 'EC', 'phone_code' => '+593', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name_en' => 'Bolivia', 'name_ar' => 'بوليفيا', 'code' => 'BO', 'phone_code' => '+591', 'currency_code' => 'BOB', 'currency_symbol' => 'Bs'],
            ['name_en' => 'Paraguay', 'name_ar' => 'باراغواي', 'code' => 'PY', 'phone_code' => '+595', 'currency_code' => 'PYG', 'currency_symbol' => '₲'],
            ['name_en' => 'Uruguay', 'name_ar' => 'أوروغواي', 'code' => 'UY', 'phone_code' => '+598', 'currency_code' => 'UYU', 'currency_symbol' => '$'],
            ['name_en' => 'Guyana', 'name_ar' => 'غويانا', 'code' => 'GY', 'phone_code' => '+592', 'currency_code' => 'GYD', 'currency_symbol' => '$'],
            ['name_en' => 'Suriname', 'name_ar' => 'سورينام', 'code' => 'SR', 'phone_code' => '+597', 'currency_code' => 'SRD', 'currency_symbol' => '$'],
            ['name_en' => 'Costa Rica', 'name_ar' => 'كوستاريكا', 'code' => 'CR', 'phone_code' => '+506', 'currency_code' => 'CRC', 'currency_symbol' => '₡'],
            ['name_en' => 'Panama', 'name_ar' => 'بنما', 'code' => 'PA', 'phone_code' => '+507', 'currency_code' => 'PAB', 'currency_symbol' => 'B/.'],
            ['name_en' => 'Guatemala', 'name_ar' => 'غواتيمالا', 'code' => 'GT', 'phone_code' => '+502', 'currency_code' => 'GTQ', 'currency_symbol' => 'Q'],
            ['name_en' => 'Honduras', 'name_ar' => 'هندوراس', 'code' => 'HN', 'phone_code' => '+504', 'currency_code' => 'HNL', 'currency_symbol' => 'L'],
            ['name_en' => 'Nicaragua', 'name_ar' => 'نيكاراغوا', 'code' => 'NI', 'phone_code' => '+505', 'currency_code' => 'NIO', 'currency_symbol' => 'C$'],
            ['name_en' => 'El Salvador', 'name_ar' => 'السلفادور', 'code' => 'SV', 'phone_code' => '+503', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name_en' => 'Belize', 'name_ar' => 'بليز', 'code' => 'BZ', 'phone_code' => '+501', 'currency_code' => 'BZD', 'currency_symbol' => 'BZ$'],
            ['name_en' => 'Cuba', 'name_ar' => 'كوبا', 'code' => 'CU', 'phone_code' => '+53', 'currency_code' => 'CUP', 'currency_symbol' => '$'],
            ['name_en' => 'Jamaica', 'name_ar' => 'جامايكا', 'code' => 'JM', 'phone_code' => '+1876', 'currency_code' => 'JMD', 'currency_symbol' => 'J$'],
            ['name_en' => 'Haiti', 'name_ar' => 'هايتي', 'code' => 'HT', 'phone_code' => '+509', 'currency_code' => 'HTG', 'currency_symbol' => 'G'],
            ['name_en' => 'Dominican Republic', 'name_ar' => 'جمهورية الدومينيكان', 'code' => 'DO', 'phone_code' => '+1809', 'currency_code' => 'DOP', 'currency_symbol' => 'RD$'],
            ['name_en' => 'Trinidad and Tobago', 'name_ar' => 'ترينيداد وتوباغو', 'code' => 'TT', 'phone_code' => '+1868', 'currency_code' => 'TTD', 'currency_symbol' => 'TT$'],
            ['name_en' => 'Bahamas', 'name_ar' => 'جزر البهاما', 'code' => 'BS', 'phone_code' => '+1242', 'currency_code' => 'BSD', 'currency_symbol' => 'B$'],
            ['name_en' => 'Barbados', 'name_ar' => 'بربادوس', 'code' => 'BB', 'phone_code' => '+1246', 'currency_code' => 'BBD', 'currency_symbol' => 'Bds$'],
            ['name_en' => 'Grenada', 'name_ar' => 'غرينادا', 'code' => 'GD', 'phone_code' => '+1473', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name_en' => 'Saint Lucia', 'name_ar' => 'سانت لوسيا', 'code' => 'LC', 'phone_code' => '+1758', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name_en' => 'Saint Vincent', 'name_ar' => 'سانت فنسنت', 'code' => 'VC', 'phone_code' => '+1784', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name_en' => 'Antigua and Barbuda', 'name_ar' => 'أنتيغوا وباربودا', 'code' => 'AG', 'phone_code' => '+1268', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name_en' => 'Saint Kitts and Nevis', 'name_ar' => 'سانت كيتس ونيفيس', 'code' => 'KN', 'phone_code' => '+1869', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name_en' => 'Dominica', 'name_ar' => 'دومينيكا', 'code' => 'DM', 'phone_code' => '+1767', 'currency_code' => 'XCD', 'currency_symbol' => '$'],

            // Asia & Pacific (48 countries)
            ['name_en' => 'China', 'name_ar' => 'الصين', 'code' => 'CN', 'phone_code' => '+86', 'currency_code' => 'CNY', 'currency_symbol' => '¥'],
            ['name_en' => 'Japan', 'name_ar' => 'اليابان', 'code' => 'JP', 'phone_code' => '+81', 'currency_code' => 'JPY', 'currency_symbol' => '¥'],
            ['name_en' => 'India', 'name_ar' => 'الهند', 'code' => 'IN', 'phone_code' => '+91', 'currency_code' => 'INR', 'currency_symbol' => '₹'],
            ['name_en' => 'South Korea', 'name_ar' => 'كوريا الجنوبية', 'code' => 'KR', 'phone_code' => '+82', 'currency_code' => 'KRW', 'currency_symbol' => '₩'],
            ['name_en' => 'Pakistan', 'name_ar' => 'باكستان', 'code' => 'PK', 'phone_code' => '+92', 'currency_code' => 'PKR', 'currency_symbol' => '₨'],
            ['name_en' => 'Bangladesh', 'name_ar' => 'بنغلاديش', 'code' => 'BD', 'phone_code' => '+880', 'currency_code' => 'BDT', 'currency_symbol' => '৳'],
            ['name_en' => 'Indonesia', 'name_ar' => 'إندونيسيا', 'code' => 'ID', 'phone_code' => '+62', 'currency_code' => 'IDR', 'currency_symbol' => 'Rp'],
            ['name_en' => 'Philippines', 'name_ar' => 'الفلبين', 'code' => 'PH', 'phone_code' => '+63', 'currency_code' => 'PHP', 'currency_symbol' => '₱'],
            ['name_en' => 'Vietnam', 'name_ar' => 'فيتنام', 'code' => 'VN', 'phone_code' => '+84', 'currency_code' => 'VND', 'currency_symbol' => '₫'],
            ['name_en' => 'Thailand', 'name_ar' => 'تايلاند', 'code' => 'TH', 'phone_code' => '+66', 'currency_code' => 'THB', 'currency_symbol' => '฿'],
            ['name_en' => 'Malaysia', 'name_ar' => 'ماليزيا', 'code' => 'MY', 'phone_code' => '+60', 'currency_code' => 'MYR', 'currency_symbol' => 'RM'],
            ['name_en' => 'Singapore', 'name_ar' => 'سنغافورة', 'code' => 'SG', 'phone_code' => '+65', 'currency_code' => 'SGD', 'currency_symbol' => 'S$'],
            ['name_en' => 'Myanmar', 'name_ar' => 'ميانمار', 'code' => 'MM', 'phone_code' => '+95', 'currency_code' => 'MMK', 'currency_symbol' => 'K'],
            ['name_en' => 'Cambodia', 'name_ar' => 'كمبوديا', 'code' => 'KH', 'phone_code' => '+855', 'currency_code' => 'KHR', 'currency_symbol' => '៛'],
            ['name_en' => 'Laos', 'name_ar' => 'لاوس', 'code' => 'LA', 'phone_code' => '+856', 'currency_code' => 'LAK', 'currency_symbol' => '₭'],
            ['name_en' => 'Brunei', 'name_ar' => 'بروناي', 'code' => 'BN', 'phone_code' => '+673', 'currency_code' => 'BND', 'currency_symbol' => 'B$'],
            ['name_en' => 'Sri Lanka', 'name_ar' => 'سريلانكا', 'code' => 'LK', 'phone_code' => '+94', 'currency_code' => 'LKR', 'currency_symbol' => 'Rs'],
            ['name_en' => 'Nepal', 'name_ar' => 'نيبال', 'code' => 'NP', 'phone_code' => '+977', 'currency_code' => 'NPR', 'currency_symbol' => 'Rs'],
            ['name_en' => 'Maldives', 'name_ar' => 'المالديف', 'code' => 'MV', 'phone_code' => '+960', 'currency_code' => 'MVR', 'currency_symbol' => 'Rf'],
            ['name_en' => 'Afghanistan', 'name_ar' => 'أفغانستان', 'code' => 'AF', 'phone_code' => '+93', 'currency_code' => 'AFN', 'currency_symbol' => '؋'],
            ['name_en' => 'Kazakhstan', 'name_ar' => 'كازاخستان', 'code' => 'KZ', 'phone_code' => '+7', 'currency_code' => 'KZT', 'currency_symbol' => '₸'],
            ['name_en' => 'Uzbekistan', 'name_ar' => 'أوزبكستان', 'code' => 'UZ', 'phone_code' => '+998', 'currency_code' => 'UZS', 'currency_symbol' => 'som'],
            ['name_en' => 'Turkmenistan', 'name_ar' => 'تركمانستان', 'code' => 'TM', 'phone_code' => '+993', 'currency_code' => 'TMT', 'currency_symbol' => 'm'],
            ['name_en' => 'Tajikistan', 'name_ar' => 'طاجيكستان', 'code' => 'TJ', 'phone_code' => '+992', 'currency_code' => 'TJS', 'currency_symbol' => 'ЅМ'],
            ['name_en' => 'Kyrgyzstan', 'name_ar' => 'قيرغيزستان', 'code' => 'KG', 'phone_code' => '+996', 'currency_code' => 'KGS', 'currency_symbol' => 'с'],
            ['name_en' => 'Mongolia', 'name_ar' => 'منغوليا', 'code' => 'MN', 'phone_code' => '+976', 'currency_code' => 'MNT', 'currency_symbol' => '₮'],
            ['name_en' => 'North Korea', 'name_ar' => 'كوريا الشمالية', 'code' => 'KP', 'phone_code' => '+850', 'currency_code' => 'KPW', 'currency_symbol' => '₩'],
            ['name_en' => 'Taiwan', 'name_ar' => 'تايوان', 'code' => 'TW', 'phone_code' => '+886', 'currency_code' => 'TWD', 'currency_symbol' => 'NT$'],
            ['name_en' => 'Hong Kong', 'name_ar' => 'هونغ كونغ', 'code' => 'HK', 'phone_code' => '+852', 'currency_code' => 'HKD', 'currency_symbol' => 'HK$'],
            ['name_en' => 'Macau', 'name_ar' => 'ماكاو', 'code' => 'MO', 'phone_code' => '+853', 'currency_code' => 'MOP', 'currency_symbol' => 'P'],
            ['name_en' => 'Australia', 'name_ar' => 'أستراليا', 'code' => 'AU', 'phone_code' => '+61', 'currency_code' => 'AUD', 'currency_symbol' => 'A$'],
            ['name_en' => 'New Zealand', 'name_ar' => 'نيوزيلندا', 'code' => 'NZ', 'phone_code' => '+64', 'currency_code' => 'NZD', 'currency_symbol' => 'NZ$'],
            ['name_en' => 'Papua New Guinea', 'name_ar' => 'بابوا غينيا الجديدة', 'code' => 'PG', 'phone_code' => '+675', 'currency_code' => 'PGK', 'currency_symbol' => 'K'],
            ['name_en' => 'Fiji', 'name_ar' => 'فيجي', 'code' => 'FJ', 'phone_code' => '+679', 'currency_code' => 'FJD', 'currency_symbol' => 'FJ$'],
            ['name_en' => 'Solomon Islands', 'name_ar' => 'جزر سليمان', 'code' => 'SB', 'phone_code' => '+677', 'currency_code' => 'SBD', 'currency_symbol' => 'SI$'],
            ['name_en' => 'Vanuatu', 'name_ar' => 'فانواتو', 'code' => 'VU', 'phone_code' => '+678', 'currency_code' => 'VUV', 'currency_symbol' => 'VT'],
            ['name_en' => 'Samoa', 'name_ar' => 'ساموا', 'code' => 'WS', 'phone_code' => '+685', 'currency_code' => 'WST', 'currency_symbol' => 'WS$'],
            ['name_en' => 'Tonga', 'name_ar' => 'تونغا', 'code' => 'TO', 'phone_code' => '+676', 'currency_code' => 'TOP', 'currency_symbol' => 'T$'],
            ['name_en' => 'Kiribati', 'name_ar' => 'كيريباتي', 'code' => 'KI', 'phone_code' => '+686', 'currency_code' => 'AUD', 'currency_symbol' => 'A$'],
            ['name_en' => 'Micronesia', 'name_ar' => 'ميكرونيزيا', 'code' => 'FM', 'phone_code' => '+691', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name_en' => 'Marshall Islands', 'name_ar' => 'جزر مارشال', 'code' => 'MH', 'phone_code' => '+692', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name_en' => 'Palau', 'name_ar' => 'بالاو', 'code' => 'PW', 'phone_code' => '+680', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name_en' => 'Nauru', 'name_ar' => 'ناورو', 'code' => 'NR', 'phone_code' => '+674', 'currency_code' => 'AUD', 'currency_symbol' => 'A$'],
            ['name_en' => 'Tuvalu', 'name_ar' => 'توفالو', 'code' => 'TV', 'phone_code' => '+688', 'currency_code' => 'AUD', 'currency_symbol' => 'A$'],
            ['name_en' => 'Timor-Leste', 'name_ar' => 'تيمور الشرقية', 'code' => 'TL', 'phone_code' => '+670', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name_en' => 'Bhutan', 'name_ar' => 'بوتان', 'code' => 'BT', 'phone_code' => '+975', 'currency_code' => 'BTN', 'currency_symbol' => 'Nu'],
            ['name_en' => 'Iran', 'name_ar' => 'إيران', 'code' => 'IR', 'phone_code' => '+98', 'currency_code' => 'IRR', 'currency_symbol' => '﷼'],
            ['name_en' => 'Azerbaijan', 'name_ar' => 'أذربيجان', 'code' => 'AZ', 'phone_code' => '+994', 'currency_code' => 'AZN', 'currency_symbol' => '₼'],

            // Africa (55 countries)
            ['name_en' => 'South Africa', 'name_ar' => 'جنوب إفريقيا', 'code' => 'ZA', 'phone_code' => '+27', 'currency_code' => 'ZAR', 'currency_symbol' => 'R'],
            ['name_en' => 'Nigeria', 'name_ar' => 'نيجيريا', 'code' => 'NG', 'phone_code' => '+234', 'currency_code' => 'NGN', 'currency_symbol' => '₦'],
            ['name_en' => 'Kenya', 'name_ar' => 'كينيا', 'code' => 'KE', 'phone_code' => '+254', 'currency_code' => 'KES', 'currency_symbol' => 'KSh'],
            ['name_en' => 'Ethiopia', 'name_ar' => 'إثيوبيا', 'code' => 'ET', 'phone_code' => '+251', 'currency_code' => 'ETB', 'currency_symbol' => 'Br'],
            ['name_en' => 'Tanzania', 'name_ar' => 'تنزانيا', 'code' => 'TZ', 'phone_code' => '+255', 'currency_code' => 'TZS', 'currency_symbol' => 'TSh'],
            ['name_en' => 'Uganda', 'name_ar' => 'أوغندا', 'code' => 'UG', 'phone_code' => '+256', 'currency_code' => 'UGX', 'currency_symbol' => 'USh'],
            ['name_en' => 'Ghana', 'name_ar' => 'غانا', 'code' => 'GH', 'phone_code' => '+233', 'currency_code' => 'GHS', 'currency_symbol' => 'GH₵'],
            ['name_en' => 'Senegal', 'name_ar' => 'السنغال', 'code' => 'SN', 'phone_code' => '+221', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name_en' => 'Ivory Coast', 'name_ar' => 'ساحل العاج', 'code' => 'CI', 'phone_code' => '+225', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name_en' => 'Cameroon', 'name_ar' => 'الكاميرون', 'code' => 'CM', 'phone_code' => '+237', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA'],
            ['name_en' => 'Zimbabwe', 'name_ar' => 'زيمبابوي', 'code' => 'ZW', 'phone_code' => '+263', 'currency_code' => 'ZWL', 'currency_symbol' => 'Z$'],
            ['name_en' => 'Zambia', 'name_ar' => 'زامبيا', 'code' => 'ZM', 'phone_code' => '+260', 'currency_code' => 'ZMW', 'currency_symbol' => 'ZK'],
            ['name_en' => 'Mozambique', 'name_ar' => 'موزمبيق', 'code' => 'MZ', 'phone_code' => '+258', 'currency_code' => 'MZN', 'currency_symbol' => 'MT'],
            ['name_en' => 'Botswana', 'name_ar' => 'بوتسوانا', 'code' => 'BW', 'phone_code' => '+267', 'currency_code' => 'BWP', 'currency_symbol' => 'P'],
            ['name_en' => 'Namibia', 'name_ar' => 'ناميبيا', 'code' => 'NA', 'phone_code' => '+264', 'currency_code' => 'NAD', 'currency_symbol' => 'N$'],
            ['name_en' => 'Angola', 'name_ar' => 'أنغولا', 'code' => 'AO', 'phone_code' => '+244', 'currency_code' => 'AOA', 'currency_symbol' => 'Kz'],
            ['name_en' => 'Rwanda', 'name_ar' => 'رواندا', 'code' => 'RW', 'phone_code' => '+250', 'currency_code' => 'RWF', 'currency_symbol' => 'FRw'],
            ['name_en' => 'Burundi', 'name_ar' => 'بوروندي', 'code' => 'BI', 'phone_code' => '+257', 'currency_code' => 'BIF', 'currency_symbol' => 'FBu'],
            ['name_en' => 'Somalia', 'name_ar' => 'الصومال', 'code' => 'SO', 'phone_code' => '+252', 'currency_code' => 'SOS', 'currency_symbol' => 'S'],
            ['name_en' => 'Djibouti', 'name_ar' => 'جيبوتي', 'code' => 'DJ', 'phone_code' => '+253', 'currency_code' => 'DJF', 'currency_symbol' => 'Fdj'],
            ['name_en' => 'Eritrea', 'name_ar' => 'إريتريا', 'code' => 'ER', 'phone_code' => '+291', 'currency_code' => 'ERN', 'currency_symbol' => 'Nfk'],
            ['name_en' => 'Mauritius', 'name_ar' => 'موريشيوس', 'code' => 'MU', 'phone_code' => '+230', 'currency_code' => 'MUR', 'currency_symbol' => '₨'],
            ['name_en' => 'Seychelles', 'name_ar' => 'سيشل', 'code' => 'SC', 'phone_code' => '+248', 'currency_code' => 'SCR', 'currency_symbol' => '₨'],
            ['name_en' => 'Madagascar', 'name_ar' => 'مدغشقر', 'code' => 'MG', 'phone_code' => '+261', 'currency_code' => 'MGA', 'currency_symbol' => 'Ar'],
            ['name_en' => 'Comoros', 'name_ar' => 'جزر القمر', 'code' => 'KM', 'phone_code' => '+269', 'currency_code' => 'KMF', 'currency_symbol' => 'CF'],
            ['name_en' => 'Malawi', 'name_ar' => 'ملاوي', 'code' => 'MW', 'phone_code' => '+265', 'currency_code' => 'MWK', 'currency_symbol' => 'MK'],
            ['name_en' => 'Lesotho', 'name_ar' => 'ليسوتو', 'code' => 'LS', 'phone_code' => '+266', 'currency_code' => 'LSL', 'currency_symbol' => 'L'],
            ['name_en' => 'Eswatini', 'name_ar' => 'إسواتيني', 'code' => 'SZ', 'phone_code' => '+268', 'currency_code' => 'SZL', 'currency_symbol' => 'E'],
            ['name_en' => 'Mali', 'name_ar' => 'مالي', 'code' => 'ML', 'phone_code' => '+223', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name_en' => 'Burkina Faso', 'name_ar' => 'بوركينا فاسو', 'code' => 'BF', 'phone_code' => '+226', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name_en' => 'Niger', 'name_ar' => 'النيجر', 'code' => 'NE', 'phone_code' => '+227', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name_en' => 'Chad', 'name_ar' => 'تشاد', 'code' => 'TD', 'phone_code' => '+235', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA'],
            ['name_en' => 'Mauritania', 'name_ar' => 'موريتانيا', 'code' => 'MR', 'phone_code' => '+222', 'currency_code' => 'MRU', 'currency_symbol' => 'UM'],
            ['name_en' => 'Benin', 'name_ar' => 'بنين', 'code' => 'BJ', 'phone_code' => '+229', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name_en' => 'Togo', 'name_ar' => 'توغو', 'code' => 'TG', 'phone_code' => '+228', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name_en' => 'Guinea', 'name_ar' => 'غينيا', 'code' => 'GN', 'phone_code' => '+224', 'currency_code' => 'GNF', 'currency_symbol' => 'FG'],
            ['name_en' => 'Sierra Leone', 'name_ar' => 'سيراليون', 'code' => 'SL', 'phone_code' => '+232', 'currency_code' => 'SLL', 'currency_symbol' => 'Le'],
            ['name_en' => 'Liberia', 'name_ar' => 'ليبيريا', 'code' => 'LR', 'phone_code' => '+231', 'currency_code' => 'LRD', 'currency_symbol' => 'L$'],
            ['name_en' => 'Gambia', 'name_ar' => 'غامبيا', 'code' => 'GM', 'phone_code' => '+220', 'currency_code' => 'GMD', 'currency_symbol' => 'D'],
            ['name_en' => 'Guinea-Bissau', 'name_ar' => 'غينيا بيساو', 'code' => 'GW', 'phone_code' => '+245', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name_en' => 'Equatorial Guinea', 'name_ar' => 'غينيا الاستوائية', 'code' => 'GQ', 'phone_code' => '+240', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA'],
            ['name_en' => 'Gabon', 'name_ar' => 'الغابون', 'code' => 'GA', 'phone_code' => '+241', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA'],
            ['name_en' => 'Congo', 'name_ar' => 'الكونغو', 'code' => 'CG', 'phone_code' => '+242', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA'],
            ['name_en' => 'DR Congo', 'name_ar' => 'الكونغو الديمقراطية', 'code' => 'CD', 'phone_code' => '+243', 'currency_code' => 'CDF', 'currency_symbol' => 'FC'],
            ['name_en' => 'Central African Republic', 'name_ar' => 'جمهورية أفريقيا الوسطى', 'code' => 'CF', 'phone_code' => '+236', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA'],
            ['name_en' => 'South Sudan', 'name_ar' => 'جنوب السودان', 'code' => 'SS', 'phone_code' => '+211', 'currency_code' => 'SSP', 'currency_symbol' => '£'],
            ['name_en' => 'Cape Verde', 'name_ar' => 'الرأس الأخضر', 'code' => 'CV', 'phone_code' => '+238', 'currency_code' => 'CVE', 'currency_symbol' => 'Esc'],
            ['name_en' => 'Sao Tome and Principe', 'name_ar' => 'ساو تومي وبرينسيبي', 'code' => 'ST', 'phone_code' => '+239', 'currency_code' => 'STN', 'currency_symbol' => 'Db'],
        ];

        foreach ($countries as $country) {
            DB::table('countries')->updateOrInsert(
                ['code' => $country['code']], // Match on code to prevent duplicates
                array_merge($country, [
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
